{"status_code":15,"lang":"python3","run_success":false,"runtime_error":"Line 30: TypeError: [[]] is not valid value for the expected return type list<list<integer>>","full_runtime_error":"TypeError: [[]] is not valid value for the expected return type list<list<integer>>\n    raise TypeError(str(ret) + \" is not valid value for the expected return type list<list<integer>>\");\nLine 30 in _driver (Solution.py)\n    _driver()\nLine 37 in <module> (Solution.py)\nDuring handling of the above exception, another exception occurred:\nTypeError: '<' not supported between instances of 'int' and 'str'\nLine 14 in _serialize_int (./python3/__serializer__.py)\nLine 63 in _serialize (./python3/__serializer__.py)\nLine 48 in <listcomp> (./python3/__serializer__.py)\nLine 48 in serialize_list (./python3/__serializer__.py)\nLine 61 in _serialize (./python3/__serializer__.py)\nLine 48 in <listcomp> (./python3/__serializer__.py)\nLine 48 in serialize_list (./python3/__serializer__.py)\nLine 61 in _serialize (./python3/__serializer__.py)\n    out = ser._serialize(ret, 'list<list<integer>>')\nLine 28 in _driver (Solution.py)","status_runtime":"N/A","memory":16300000,"question_id":"78","elapsed_time":51,"compare_result":"0000000000","code_output":"","std_output":"","last_testcase":"[1,2,3]","expected_output":"[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]","task_finish_time":1695429799971,"task_name":"judger.judgetask.Judge","finished":true,"total_correct":0,"total_testcases":10,"runtime_percentile":null,"status_memory":"N/A","memory_percentile":null,"pretty_lang":"Python3","submission_id":"1056716202","status_msg":"Runtime Error","state":"SUCCESS"}