{"status_code":15,"lang":"python3","run_success":false,"runtime_error":"Line 46: TypeError: [[2,2,3],[7]] is not valid value for the expected return type list<list<integer>>","full_runtime_error":"TypeError: [[2,2,3],[7]] is not valid value for the expected return type list<list<integer>>\n    raise TypeError(str(ret) + \" is not valid value for the expected return type list<list<integer>>\");\nLine 46 in _driver (Solution.py)\n    _driver()\nLine 53 in <module> (Solution.py)\nDuring handling of the above exception, another exception occurred:\nTypeError: '<' not supported between instances of 'int' and 'str'\nLine 14 in _serialize_int (./python3/__serializer__.py)\nLine 63 in _serialize (./python3/__serializer__.py)\nLine 48 in <listcomp> (./python3/__serializer__.py)\nLine 48 in serialize_list (./python3/__serializer__.py)\nLine 61 in _serialize (./python3/__serializer__.py)\nLine 48 in <listcomp> (./python3/__serializer__.py)\nLine 48 in serialize_list (./python3/__serializer__.py)\nLine 61 in _serialize (./python3/__serializer__.py)\n    out = ser._serialize(ret, 'list<list<integer>>')\nLine 44 in _driver (Solution.py)","status_runtime":"N/A","memory":16280000,"question_id":"39","elapsed_time":51,"compare_result":"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","code_output":"","std_output":"","last_testcase":"[2,3,6,7]\n7","expected_output":"[[2,2,3],[7]]","task_finish_time":1695430619555,"task_name":"judger.judgetask.Judge","finished":true,"total_correct":0,"total_testcases":160,"runtime_percentile":null,"status_memory":"N/A","memory_percentile":null,"pretty_lang":"Python3","submission_id":"1056720404","status_msg":"Runtime Error","state":"SUCCESS"}